export const MANAGE_INVESTMENTS_BASE_ROUTE = '../investment/manage/';
export const MANAGE_INVESTMENTS_ROUTES = {
  ROOT: 'overview',
  YOUR_INVESTMENT: 'overview',
  YOUR_PORTFOLIO: 'portfolio',
  TOPUP: 'portfolio/top-up',
  TOPUP_STATUS: 'portfolio/top-up/status',
  WITHDRAWAL: 'portfolio/withdrawal',
  WITHDRAWAL_PAYMENT_METHOD: 'portfolio/withdrawal/bank-account',
  WITHDRAWAL_SUCCESS: 'portfolio/withdrawal/status',
  TRANSACTION: 'portfolio/transactions',
  HOLDINGS: 'portfolio/holdings',
  ASSET_ALLOCATION: 'portfolio/asset-allocation',
  FUND_DETAILS: 'fund-details'
};
export const MANAGE_INVESTMENTS_ROUTE_PATHS = {
  ROOT: MANAGE_INVESTMENTS_BASE_ROUTE + MANAGE_INVESTMENTS_ROUTES.ROOT,
  YOUR_INVESTMENT: MANAGE_INVESTMENTS_BASE_ROUTE + MANAGE_INVESTMENTS_ROUTES.YOUR_INVESTMENT,
  YOUR_PORTFOLIO:
    MANAGE_INVESTMENTS_BASE_ROUTE + MANAGE_INVESTMENTS_ROUTES.YOUR_PORTFOLIO,
  TOPUP: MANAGE_INVESTMENTS_BASE_ROUTE + MANAGE_INVESTMENTS_ROUTES.TOPUP,
  TOPUP_STATUS: MANAGE_INVESTMENTS_BASE_ROUTE + MANAGE_INVESTMENTS_ROUTES.TOPUP_STATUS,
  WITHDRAWAL: MANAGE_INVESTMENTS_BASE_ROUTE + MANAGE_INVESTMENTS_ROUTES.WITHDRAWAL,
  WITHDRAWAL_SUCCESS:
    MANAGE_INVESTMENTS_BASE_ROUTE + MANAGE_INVESTMENTS_ROUTES.WITHDRAWAL_SUCCESS,
  WITHDRAWAL_PAYMENT_METHOD:
    MANAGE_INVESTMENTS_BASE_ROUTE + MANAGE_INVESTMENTS_ROUTES.WITHDRAWAL_PAYMENT_METHOD,
  TRANSACTION: MANAGE_INVESTMENTS_BASE_ROUTE + MANAGE_INVESTMENTS_ROUTES.TRANSACTION,
  HOLDINGS: MANAGE_INVESTMENTS_BASE_ROUTE + MANAGE_INVESTMENTS_ROUTES.HOLDINGS,
  ASSET_ALLOCATION:
    MANAGE_INVESTMENTS_BASE_ROUTE + MANAGE_INVESTMENTS_ROUTES.ASSET_ALLOCATION,
  FUND_DETAILS: MANAGE_INVESTMENTS_BASE_ROUTE + MANAGE_INVESTMENTS_ROUTES.FUND_DETAILS
};
