export const MANAGEMENT_BASE_ROUTE = '../investment/';
export const MANAGEMENT_ROUTES = {
  ROOT: '',
  YOUR_INVESTMENT: 'overview',
  FUND_YOUR_ACCOUNT: 'portfolio/fund-your-account',
  TOPUP: 'portfolio/top-up',
  TOPUP_REQUEST: 'portfolio/topup-request',
  YOUR_PORTFOLIO: 'portfolio',
  WITHDRAWAL: 'portfolio/withdraw',
  WITHDRAWAL_PAYMENT_METHOD: 'portfolio/withdrawal-payment-method',
  WITHDRAWAL_SUCCESS: 'portfolio/withdrawal-success',
  TRANSACTION: 'portfolio/transaction',
  HOLDINGS: 'portfolio/holdings',
  ASSET_ALLOCATION: 'asset-allocation',
  FUND_DETAILS: 'fund-details'
};
export const MANAGEMENT_ROUTE_PATHS = {
  ROOT: MANAGEMENT_BASE_ROUTE + MANAGEMENT_ROUTES.ROOT,
  YOUR_INVESTMENT: MANAGEMENT_BASE_ROUTE,
  YOUR_PORTFOLIO:
    MANAGEMENT_BASE_ROUTE + MANAGEMENT_ROUTES.YOUR_PORTFOLIO,
  FUND_YOUR_ACCOUNT:
    MANAGEMENT_BASE_ROUTE + MANAGEMENT_ROUTES.FUND_YOUR_ACCOUNT,
  TOPUP: MANAGEMENT_BASE_ROUTE + MANAGEMENT_ROUTES.TOPUP,
  TOPUP_REQUEST: MANAGEMENT_BASE_ROUTE + MANAGEMENT_ROUTES.TOPUP_REQUEST,
  WITHDRAWAL: MANAGEMENT_BASE_ROUTE + MANAGEMENT_ROUTES.WITHDRAWAL,
  WITHDRAWAL_SUCCESS:
    MANAGEMENT_BASE_ROUTE + MANAGEMENT_ROUTES.WITHDRAWAL_SUCCESS,
  WITHDRAWAL_PAYMENT_METHOD:
    MANAGEMENT_BASE_ROUTE + MANAGEMENT_ROUTES.WITHDRAWAL_PAYMENT_METHOD,
  TRANSACTION: MANAGEMENT_BASE_ROUTE + MANAGEMENT_ROUTES.TRANSACTION,
  HOLDINGS: MANAGEMENT_BASE_ROUTE + MANAGEMENT_ROUTES.HOLDINGS,
  ASSET_ALLOCATION:
    MANAGEMENT_BASE_ROUTE + MANAGEMENT_ROUTES.ASSET_ALLOCATION,
  FUND_DETAILS: MANAGEMENT_BASE_ROUTE + MANAGEMENT_ROUTES.FUND_DETAILS
};
