export const INVESTMENT_ACCOUNT_BASE_ROUTE = '../investment-account/';

export const INVESTMENT_ACCOUNT_ROUTES = {
  ROOT: '',
  SELECT_NATIONALITY: 'select-nationality',
  PERSONAL_INFO: 'personal-info',
  RESIDENTIAL_ADDRESS: 'residential-address',
  EMPLOYMENT_DETAILS: 'employment-details',
  TAX_INFO: 'tax-info'
};

export const INVESTMENT_ACCOUNT_ROUTE_PATHS = {
  ROOT: '',
  PERSONAL_INFO: INVESTMENT_ACCOUNT_BASE_ROUTE + INVESTMENT_ACCOUNT_ROUTES.PERSONAL_INFO,
  RESIDENTIAL_ADDRESS: INVESTMENT_ACCOUNT_BASE_ROUTE + INVESTMENT_ACCOUNT_ROUTES.RESIDENTIAL_ADDRESS,
  SELECT_NATIONALITY: INVESTMENT_ACCOUNT_BASE_ROUTE + INVESTMENT_ACCOUNT_ROUTES.SELECT_NATIONALITY,
  EMPLOYMENT_DETAILS: INVESTMENT_ACCOUNT_BASE_ROUTE + INVESTMENT_ACCOUNT_ROUTES.EMPLOYMENT_DETAILS,
  TAX_INFO: INVESTMENT_ACCOUNT_BASE_ROUTE + INVESTMENT_ACCOUNT_ROUTES.TAX_INFO
};
