export const INVESTMENT_ACCOUNT_BASE_ROUTE = '../investment-account/';

export const INVESTMENT_ACCOUNT_ROUTES = {
  ROOT: '',
  PERSONAL_INFO: 'personal-info',
  RESIDENTIAL_ADDRESS: 'residential-address',
  SELECT_NATIONALITY: 'select-nationality'
};

export const INVESTMENT_ACCOUNT_ROUTE_PATHS = {
  ROOT: '',
  PERSONAL_INFO: INVESTMENT_ACCOUNT_BASE_ROUTE + INVESTMENT_ACCOUNT_ROUTES.PERSONAL_INFO,
  RESIDENTIAL_ADDRESS: INVESTMENT_ACCOUNT_BASE_ROUTE + INVESTMENT_ACCOUNT_ROUTES.RESIDENTIAL_ADDRESS,
  SELECT_NATIONALITY: INVESTMENT_ACCOUNT_BASE_ROUTE + INVESTMENT_ACCOUNT_BASE_ROUTE.SELECT_NATIONALITY
};