
<style>.embed-container { position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%; height: auto; } .embed-container iframe, .embed-container object, .embed-container embed { position: absolute; top: 0; left: 0; width: 100%; height: 100%; }</style><div class='embed-container'><iframe src='https://www.youtube.com/embed/OW9gNHosbBU?autoplay=0&rel=0' frameborder='0' allowfullscreen></iframe></div>
<br>
<p><strong>Transcript</strong></p>
<p>Hi, welcome to Do It Your-way Insurance, an  insurance portal that is dedicated to help you make good insurance decisions.  The thing about insurance is this; many of us know the importance of buying  insurance. However, we don&rsquo;t enjoy the process of buying it. Plus, we don&rsquo;t  know enough to do it ourselves. And we were made to believe that buying  insurance is very expensive and it is impossible to cover ourselves  sufficiently. How would you like today if you can know what you need to know  about insurance?</p>

<p>Buy them at a much lower cost without  having to go through that process? This is precisely why we have developed  DIYInsurance. Otherwise, known as Do It Your-way, not Do It Yourself Insurance.  It is a portal that will allow you to know enough about insurance and if you  want to buy it, you can buy it at a much lower cost without having to go  through that very uncomfortable sales process. </p>

<p>  How do we do it? We put up videos to  educate you, we put up tools to help you discover your own insurance needs and  we put together the first insurance aggregator in Singapore that helps you  compare the insurance, all the insurances that are available on the portal, you  will be able to know the features, the benefits. You can do it yourself, there  is no need to ask anyone. Through that, we hope that you will be able to cover  yourself sufficiently and cover yourself at a much lower cost. </p>

<p>  For more than 10 years, Providend has been  championing this cause. We believe that the industry has to change. Today, it  is just too expensive. There is a need to lower the cost, there is a need to be  more transparent. And we believe the  only way to do it, is if you as the consumer lead the way. If you buy it this  way, if you do it your way, then the industry has no choice but to lower cost.  We ask you to join us in this movement because we believe that if we do it  together, we can achieve it. </p>
<p>Thank you for watching this video, if you find  this video interesting, please share it with your friends. Alternatively, you  can also subscribe to our YouTube channel or like our Facebook page or join  Club DIY.</p>