<img src="/assets/articles/images/35/thumbnail.jpg" class="pull-right thumbnail" style=" padding:10px;">
<p>Since 2003, we have been advocating the use of <a href="https://www.moneyowl.com.sg/articles/entry/59" target="_blank" title="Why Most Needs can be covered by Term Insurance" target="_blank">term insurance</a>. While many Singaporeans appreciated our beliefs, the insurance and financial planning industry fought it. We stood out like a sore thumb and were a lone voice. So it was very encouraging for me when during the NTUC Income's 40th anniversary dinner 2 weeks ago, Senior Minister Goh Chok Tong supported the use of term insurances and even asked insurers to put more emphasis on it.</p>
<br/>
<p>So, why our belief in using term insurances?</p>
<br/>
<p> Some of the biggest risks in life include loss of income due to death, disability and a medical crisis. When we retire and no longer earn and need an income, we no longer face these risks and as such no longer need insurance protection for it. As such, buying permanent cover using expensive whole life insurance means paying for something that you don't need and likely can't afford. So Singaporeans end up being grossly under covered. </p>
<br/>
<p>One of the main objections given to people against buying <a href="https://www.moneyowl.com.sg/articles/entry/59" target="_blank" title="Why Most Needs can be covered by Term Insurance" target="_blank">term insurance</a> is that when the insurance expires, you get nothing back. While this is true, it is only half a truth. This is because; this is the same for whole life plans too. For every dollar you pay as premium for your whole life plans, a portion of it goes into paying the mortality charge that provides you the cover you need. The rest of it is invested into the insurance company's life fund. The mortality charge portion is never returned back to you. The only reason why you get money back from a whole life plan is because you gave the insurance companies extra money to The only reason why you get money back from a whole life plan is because you gave the insurance companies extra money to invest. Written by Christopher Tan invest. When you buy a term plan, you are effectively paying only for the mortality charge; you are just buying pure protection. </p>
<br/>
<p>For the longest time, we have been told that we can use insurance for protection as well as savings towards our financial goals. The irony of this is that the returns of insurance is insufficient to help us reach our goals and whole life insurance is so expensive that it won't protect us fully as well. So buying whole life insurance achieves neither goal. When we buy term insurance, we can at least achieve the protection goal, which is the priority and foundation to all good financial plans. Then, with proper advice and coaching, we can use the savings from not buying a whole life plan to invest and reach our goals. We now have a chance to achieve both goals. Even if you are very conservative, there are many other optional instruments; there is no need to use insurance. Insurance is for protection only - the word "insurance" suggests so.</p>
<!--
<div class="text-xs-center"><a href="https://www.moneyowl.com.sg/direct">
  <img src="assets/images/banners/compare_pro_540w.png" alt="direct protection plans"></a>
</div>-->
<br><br>
<p>If the advantages of term plans are so clear, why are they not frequently bought? There are many reasons, but editorial space only allows me to highlight the 2 main ones. I call them the 2 "lacks" of salespeople. The first is the lack of knowledge and second, lack of motivation. When I started out in this profession about 14 years ago, I spent a short time with an insurance company. I can count the number of times we were trained in the use of <a href="https://www.moneyowl.com.sg/articles/entry/59" target="_blank" title="Why Most Needs can be covered by Term Insurance" target="_blank">term insurances</a>. The emphasis was always on "with-profits" products. But I think the biggest hindrance to term plans is the salespeople's lack of motivation. It is obvious that the commissions pay out for a whole life plan is a lot more than a term plan. In this commissions-hungry industry where salespeople are rewarded for sales more than advice, whole life plans will always be sold. That is why I avoided the use of "advisers" throughout this writing and used "salespeople" instead. This is not to say there aren't good salespeople or even advisers out there. Unfortunately, they are in the minority. I know of some who will insist on recommending term insurances despite earning less. To these people, I salute them. But the fact still remains that for the majority, compensation drives behaviour. I speak at seminars to thousands of people each year, and each time I ask why they don't buy term insurances, most tell me that their agents or advisers would not sell it to them. Even if they did, they would package some whole life plans together with it, on the basis of "playing safe" just in case they need it for their entire life.</p>
<br/>
<p>About 2 months ago, I asked an actuary (someone who designs insurance products) who has left an insurance company what he buys for himself. Like many ex-actuaries I have spoken to, he said he would never buy an investment-linked plan or a whole life plan as it is just too expensive and doesn't make sense. He has protected his family with term plans. So, if the chef doesn't eat his own cooking, why should we? </P>
<br/>
<p>SM Goh pointed out that it is the advisers that wield the greatest influence on the type of plan a person purchases. I agree. We have been advocating term insurance for the past 7 years and not very much has changed. I believe real change will come when Singaporeans understand what insurance is for and begin to insist on term insurance. Salespeople will then have no choice but to sell it. It is a shame that clients have to tell this industry the right thing to do. But in this case of term insurance, it is the only way things will change. I look forward to the day when we have an advisory industry and not a sales one. </p>
<br/>
<p class="text-muted"><em>This is an original article written by Christopher Tan, CEO of Providend. the edited copy appeared in The Sunday Times (Invest) on 7 November 2010 titled "For Good Terms, Buy Term Insurance"</em></p>