<style>.embed-container { position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%; height: auto; } .embed-container iframe, .embed-container object, .embed-container embed { position: absolute; top: 0; left: 0; width: 100%; height: 100%; }</style><div class='embed-container'><iframe src='https://www.youtube.com/embed/QpIAtxoBAjI?autoplay=0&rel=0' frameborder='0' allowfullscreen></iframe></div>
<br>
<p><strong>Transcript</strong></p>
<p>Most of us know why it&rsquo;s important for us  to have life insurance and to have enough, it is to provide security for us and  our loved ones. However, we just don&rsquo;t enjoy the process of buying insurance.  There&rsquo;s so many products and it can be confusing. To make matters worse, when  we are recommended on what to buy, we never really know whether it is done in  our best interest. At time, we feel pressured into buying. Wouldn&rsquo;t it be  great, if you do your own insurance planning in an easy and efficient way? </p>
<p>  Now you can, with Do It Your-way Insurance.  DIY has helped thousands of people save money on their insurance needs. DIY is  a platform where you decide what insurance you need, how much you need and how  you want to buy it. </p>
<p>  The Selfcheck function becomes your digital  adviser that does a proper checkup and assessment of your life insurance needs  automatically. It also lets you know if you have a surplus or shortfall in your  current insurance coverage. In the case of a shortfall, the tool compares  different plans for you and recommends the highest ranked policy which is  closest to your needs. </p>
<p>  DIY will also automatically match you with  a salaried-based financial adviser if you require further advice or help and we  will also rebate commissions back to you on the policy you choose. Since there  is no obligation to buy anything, this gives you total freedom to choose what&rsquo;s  best for you without any sales pressure.</p>
<p>  Find out why thousands of users trust DIY  for their insurance needs. Give it a try for yourself to help ensure that your  family and your<a name="_GoBack"></a>self can be covered sufficiently and in  the most cost-effective manner.</p>


