export const MANAGEMENT_BASE_ROUTE = '../investment/';
export const MANAGEMENT_ROUTES = {
  ROOT: 'overview',
  YOUR_INVESTMENT: 'overview',
  YOUR_PORTFOLIO: 'portfolio',
  TOPUP: 'portfolio/top-up',
  FUNDING_INSTRUCTIONS: 'portfolio/top-up/funding-instructions',
  TOPUP_STATUS: 'portfolio/top-up/status',
  WITHDRAWAL: 'portfolio/withdrawal',
  WITHDRAWAL_PAYMENT_METHOD: 'portfolio/withdrawal/bank-account',
  WITHDRAWAL_SUCCESS: 'portfolio/withdrawal/status',
  TRANSACTION: 'portfolio/transactions',
  HOLDINGS: 'portfolio/holdings',
  ASSET_ALLOCATION: 'portfolio/asset-allocation',
  FUND_DETAILS: 'fund-details'
};
export const MANAGEMENT_ROUTE_PATHS = {
  ROOT: MANAGEMENT_BASE_ROUTE + MANAGEMENT_ROUTES.ROOT,
  YOUR_INVESTMENT: MANAGEMENT_BASE_ROUTE,
  YOUR_PORTFOLIO:
    MANAGEMENT_BASE_ROUTE + MANAGEMENT_ROUTES.YOUR_PORTFOLIO,
  FUNDING_INSTRUCTIONS:
    MANAGEMENT_BASE_ROUTE + MANAGEMENT_ROUTES.FUNDING_INSTRUCTIONS,
  TOPUP: MANAGEMENT_BASE_ROUTE + MANAGEMENT_ROUTES.TOPUP,
  TOPUP_STATUS: MANAGEMENT_BASE_ROUTE + MANAGEMENT_ROUTES.TOPUP_STATUS,
  WITHDRAWAL: MANAGEMENT_BASE_ROUTE + MANAGEMENT_ROUTES.WITHDRAWAL,
  WITHDRAWAL_SUCCESS:
    MANAGEMENT_BASE_ROUTE + MANAGEMENT_ROUTES.WITHDRAWAL_SUCCESS,
  WITHDRAWAL_PAYMENT_METHOD:
    MANAGEMENT_BASE_ROUTE + MANAGEMENT_ROUTES.WITHDRAWAL_PAYMENT_METHOD,
  TRANSACTION: MANAGEMENT_BASE_ROUTE + MANAGEMENT_ROUTES.TRANSACTION,
  HOLDINGS: MANAGEMENT_BASE_ROUTE + MANAGEMENT_ROUTES.HOLDINGS,
  ASSET_ALLOCATION:
    MANAGEMENT_BASE_ROUTE + MANAGEMENT_ROUTES.ASSET_ALLOCATION,
  FUND_DETAILS: MANAGEMENT_BASE_ROUTE + MANAGEMENT_ROUTES.FUND_DETAILS
};
