// Production release path
export const ENGAGEMENT_JOURNEY_BASE_ROUTE = '../investment/';
// Soft release path
// export const ENGAGEMENT_JOURNEY_BASE_ROUTE = '../20190316invest/';

export const ENGAGEMENT_JOURNEY_ROUTES = {
  ROOT: '',
  START: 'start-journey',
  GET_STARTED_STEP1: 'step-1',
  PERSONAL_INFO: 'investment-period',
  MY_FINANCIALS: 'your-financials',
  GET_STARTED_STEP2: 'step-2',
  RISK_ASSESSMENT: 'risk-willingness',
  RISK_PROFILE: 'recommendation',
  PORTFOLIO_RECOMMENDATION: 'portfolio-details',
  WHATS_THE_RISK: 'whats-the-risk',
  FUND_DETAILS: 'fund-details',
  PORTFOLIO_EXIST: 'portfolio-exist'
};

export const ENGAGEMENT_JOURNEY_ROUTE_PATHS = {
  ROOT: ENGAGEMENT_JOURNEY_BASE_ROUTE + ENGAGEMENT_JOURNEY_ROUTES.ROOT,
  GET_STARTED_STEP1: ENGAGEMENT_JOURNEY_BASE_ROUTE + ENGAGEMENT_JOURNEY_ROUTES.GET_STARTED_STEP1,
  PORTFOLIO_EXIST: ENGAGEMENT_JOURNEY_BASE_ROUTE + ENGAGEMENT_JOURNEY_ROUTES.PORTFOLIO_EXIST,
  PERSONAL_INFO: ENGAGEMENT_JOURNEY_BASE_ROUTE + ENGAGEMENT_JOURNEY_ROUTES.PERSONAL_INFO,
  MY_FINANCIALS: ENGAGEMENT_JOURNEY_BASE_ROUTE + ENGAGEMENT_JOURNEY_ROUTES.MY_FINANCIALS,
  GET_STARTED_STEP2: ENGAGEMENT_JOURNEY_BASE_ROUTE + ENGAGEMENT_JOURNEY_ROUTES.GET_STARTED_STEP2,
  RISK_ASSESSMENT: ENGAGEMENT_JOURNEY_BASE_ROUTE + ENGAGEMENT_JOURNEY_ROUTES.RISK_ASSESSMENT,
  RISK_PROFILE: ENGAGEMENT_JOURNEY_BASE_ROUTE + ENGAGEMENT_JOURNEY_ROUTES.RISK_PROFILE,
  PORTFOLIO_RECOMMENDATION:
    ENGAGEMENT_JOURNEY_BASE_ROUTE + ENGAGEMENT_JOURNEY_ROUTES.PORTFOLIO_RECOMMENDATION,
  WHATS_THE_RISK: ENGAGEMENT_JOURNEY_BASE_ROUTE + ENGAGEMENT_JOURNEY_ROUTES.WHATS_THE_RISK,
  FUND_DETAILS: ENGAGEMENT_JOURNEY_BASE_ROUTE + ENGAGEMENT_JOURNEY_ROUTES.FUND_DETAILS,
  START: ENGAGEMENT_JOURNEY_BASE_ROUTE + ENGAGEMENT_JOURNEY_ROUTES.START
};
