export const DIRECT_BASE_ROUTE = '../direct/';

export const DIRECT_ROUTES = {
  ROOT: '',
  RESULTS: 'results',
  COMPARE_PLANS: 'compare-plans'
};

export const DIRECT_ROUTE_PATHS = {
  ROOT: '',
  RESULTS: DIRECT_BASE_ROUTE + DIRECT_ROUTES.RESULTS,
  COMPARE_PLANS: DIRECT_BASE_ROUTE + DIRECT_ROUTES.COMPARE_PLANS
};
