export const TOPUP_AND_WITHDRAW_BASE_ROUTE = '../topup-and-withdraw/';

export const TOPUP_AND_WITHDRAW_ROUTES = {
  ROOT: '',
  TOPUP: 'top-up',
  TOPUP_REQUEST: 'topup-request',
  YOUR_INVESY_TMENT: 'your-investment',
  YOUR_PORTFOLIO: 'your-portfolio',
  ASSET_ALLOCATION: 'asset-allocation'

};

export const TOPUP_AND_WITHDRAW_ROUTE_PATHS = {
  ROOT: '',
  TOPUP: TOPUP_AND_WITHDRAW_BASE_ROUTE + TOPUP_AND_WITHDRAW_ROUTES.TOPUP,
  TOPUP_REQUEST: TOPUP_AND_WITHDRAW_BASE_ROUTE + TOPUP_AND_WITHDRAW_ROUTES.TOPUP_REQUEST,
  YOUR_INVESY_TMENT: TOPUP_AND_WITHDRAW_BASE_ROUTE + TOPUP_AND_WITHDRAW_ROUTES.YOUR_INVESY_TMENT,
  YOUR_PORTFOLIO: TOPUP_AND_WITHDRAW_BASE_ROUTE + TOPUP_AND_WITHDRAW_ROUTES.YOUR_PORTFOLIO,
  ASSET_ALLOCATION: TOPUP_AND_WITHDRAW_BASE_ROUTE + TOPUP_AND_WITHDRAW_ROUTES.ASSET_ALLOCATION
};
