export const TOPUP_AND_WITHDRAW_BASE_ROUTE = '../topup-and-withdraw/';

export const TOPUP_AND_WITHDRAW_ROUTES = {
  ROOT: '',
  TOPUP: 'top-up',
  TOPUP_REQUEST: 'topup-request',
  WITHDRAWAL: 'withdraw',
  WITHDRAWAL_SUCCESS: 'withdrawal-success'
};

export const TOPUP_AND_WITHDRAW_ROUTE_PATHS = {
  ROOT: '',
  TOPUP: TOPUP_AND_WITHDRAW_BASE_ROUTE + TOPUP_AND_WITHDRAW_ROUTES.TOPUP,
  TOPUP_REQUEST: TOPUP_AND_WITHDRAW_BASE_ROUTE + TOPUP_AND_WITHDRAW_ROUTES.TOPUP_REQUEST,
  WITHDRAWAL: TOPUP_AND_WITHDRAW_BASE_ROUTE + TOPUP_AND_WITHDRAW_ROUTES.WITHDRAWAL,
  WITHDRAWAL_SUCCESS: TOPUP_AND_WITHDRAW_BASE_ROUTE + TOPUP_AND_WITHDRAW_ROUTES.WITHDRAWAL_SUCCESS
};
