export const TOPUP_AND_WITHDRAW_BASE_ROUTE = '../topup-and-withdraw/';

export const TOPUP_AND_WITHDRAW_ROUTES = {
  ROOT: '',
  TOPUP: 'top-up',
  TOPUP_REQUEST: 'topup-request',
<<<<<<< HEAD
  YOUR_INVESY_TMENT: 'your-investment',
  YOUR_PORTFOLIO: 'your-portfolio',
  ASSET_ALLOCATION: 'asset-allocation'

=======
  WITHDRAWAL: 'withdraw',
  WITHDRAWAL_PAYMENT_METHOD: 'withdrawal-payment-method',
  WITHDRAWAL_SUCCESS: 'withdrawal-success'
>>>>>>> 44d4eaaa9e13555b6941a1981f01fb230fd268d3
};

export const TOPUP_AND_WITHDRAW_ROUTE_PATHS = {
  ROOT: '',
  TOPUP: TOPUP_AND_WITHDRAW_BASE_ROUTE + TOPUP_AND_WITHDRAW_ROUTES.TOPUP,
  TOPUP_REQUEST: TOPUP_AND_WITHDRAW_BASE_ROUTE + TOPUP_AND_WITHDRAW_ROUTES.TOPUP_REQUEST,
<<<<<<< HEAD
  YOUR_INVESY_TMENT: TOPUP_AND_WITHDRAW_BASE_ROUTE + TOPUP_AND_WITHDRAW_ROUTES.YOUR_INVESY_TMENT,
  YOUR_PORTFOLIO: TOPUP_AND_WITHDRAW_BASE_ROUTE + TOPUP_AND_WITHDRAW_ROUTES.YOUR_PORTFOLIO,
  ASSET_ALLOCATION: TOPUP_AND_WITHDRAW_BASE_ROUTE + TOPUP_AND_WITHDRAW_ROUTES.ASSET_ALLOCATION
=======
  WITHDRAWAL: TOPUP_AND_WITHDRAW_BASE_ROUTE + TOPUP_AND_WITHDRAW_ROUTES.WITHDRAWAL,
  WITHDRAWAL_SUCCESS: TOPUP_AND_WITHDRAW_BASE_ROUTE + TOPUP_AND_WITHDRAW_ROUTES.WITHDRAWAL_SUCCESS,
  WITHDRAWAL_PAYMENT_METHOD: TOPUP_AND_WITHDRAW_BASE_ROUTE + TOPUP_AND_WITHDRAW_ROUTES.WITHDRAWAL_PAYMENT_METHOD
>>>>>>> 44d4eaaa9e13555b6941a1981f01fb230fd268d3
};
