export const myInfoResponseMapping = {
    "cpfbalances": ["cpfbalances", "total"],
    "uinfin": ["uin"],
    "name": ["name", "value"],
    "sex": ["sex", "desc"],
    "dob": ["dob", "value"],
    "regadd": ["regadd", "formattedSingleLineAddress"],
    "mobileno": ["mobileno", "nbr"],
    "email": ["email", "value"],
    "nationality": ["nationality", "desc"],
    "residentialstatus": ["residentialstatus", "desc"],
    "birthcountry": ["birthcountry", "desc"],
    "cpfhousingwithdrawal": ["cpfhousingwithdrawal", "withdrawaldetails", 0, "principalwithdrawalamt"],
    "noa": ["noa", "amount"],
    "childrenbirthrecords.name": ["childrenRecords", 0, "name", "value"],
    "childrenbirthrecords.sex": ["childrenRecords", 0, "sex", "desc"],
    "childrenbirthrecords.dob": ["childrenRecords", 0, "dob", "value"],
    "childrenbirthrecords.lifestatus": ["childrenRecords", 0, "lifeStatus", "desc"],
    "sponsoredchildrenrecords.name": ["sponsoredChildrenRecords", 0, "name", "value"],
    "sponsoredchildrenrecords.sex": ["sponsoredChildrenRecords", 0, "sex", "desc"],
    "sponsoredchildrenrecords.dob": ["sponsoredChildrenRecords", 0, "dob", "value"],
    "sponsoredchildrenrecords.lifestatus": ["sponsoredChildrenRecords", 0, "lifeStatus", "desc"],
    "sponsoredchildrenrecords.residentialstatus": ["sponsoredChildrenRecords", 0, "residentialStatus", "desc"],
    "hdbownership.dateofpurchase": ["hdbOwnerships", 0, "dateOfPurchase"],
    "hdbownership.loangranted": ["hdbOwnerships", 0, "loanGranted"],
    "hdbownership.outstandingloanbalance": ["hdbOwnerships", 0, "outstandingLoanBalance"],
    "hdbownership.monthlyloaninstalment": ["hdbOwnerships", 0, "monthlyLoanInstalment"],
    "vehicles.firstregistrationdate": ["vehicles", 0, "firstRegistrationDate"],
    "vehicles.coeexpirydate": ["vehicles", 0, "coeExpiryDate"],
    "vehicles.openmarketvalue": ["vehicles", 0, "openMarketValue"],
    "vehicles.status": ["vehicles", 0, "status"],
};
