export const COMPREHENSIVE_BASE_ROUTE = '../comprehensive/';

export const COMPREHENSIVE_ROUTES = {
    ROOT: '',
    STEPS: 'steps',
    DEPENDANT_SELECTION: 'dependant-selection',
    DEPENDANT_DETAILS: 'dependant-details',
    DEPENDANT_EDUCATION: 'dependant-education',
    DEPENDANT_EDUCATION_LIST: 'dependant-education-list',
    DEPENDANT_EDUCATION_PREFERENCE: 'dependant-education-preference',
    MY_EARNINGS: 'my-earnings',
    GETTING_STARTED: 'getting-started',

};

export const COMPREHENSIVE_ROUTE_PATHS = {
    ROOT: '',
    STEPS: COMPREHENSIVE_BASE_ROUTE + COMPREHENSIVE_ROUTES.STEPS,
    DEPENDANT_SELECTION: COMPREHENSIVE_BASE_ROUTE + COMPREHENSIVE_ROUTES.DEPENDANT_SELECTION,
    DEPENDANT_DETAILS: COMPREHENSIVE_BASE_ROUTE + COMPREHENSIVE_ROUTES.DEPENDANT_DETAILS,
    DEPENDANT_EDUCATION: COMPREHENSIVE_BASE_ROUTE + COMPREHENSIVE_ROUTES.DEPENDANT_EDUCATION,
    DEPENDANT_EDUCATION_LIST: COMPREHENSIVE_BASE_ROUTE + COMPREHENSIVE_ROUTES.DEPENDANT_EDUCATION_LIST,
    DEPENDANT_EDUCATION_PREFERENCE:  COMPREHENSIVE_BASE_ROUTE + COMPREHENSIVE_ROUTES. DEPENDANT_EDUCATION_PREFERENCE,
    MY_EARNINGS: COMPREHENSIVE_BASE_ROUTE + COMPREHENSIVE_ROUTES.MY_EARNINGS,
    GETTING_STARTED: COMPREHENSIVE_BASE_ROUTE + COMPREHENSIVE_ROUTES.GETTING_STARTED
};
