export const COMPREHENSIVE_BASE_ROUTE = '../comprehensive/';

export const COMPREHENSIVE_ROUTES = {
    ROOT: '',
    STEPS: 'steps',
    SHOULDERS: 'shoulders'

};

export const COMPREHENSIVE_ROUTE_PATHS = {
    ROOT: '',
    STEPS: COMPREHENSIVE_BASE_ROUTE + COMPREHENSIVE_ROUTES.STEPS,
    SHOULDERS: COMPREHENSIVE_BASE_ROUTE + COMPREHENSIVE_ROUTES.SHOULDERS
};
