export const GUIDE_ME_BASE_ROUTE = '../guideme/';

export const GUIDE_ME_ROUTES = {
  ROOT: '',
  PROFILE: 'profile',
  GET_STARTED: 'getstarted',
  FINANCIAL_ASSESSMENT: 'financial-assessment',
  INSURE_ASSESSMENT: 'insure-assessment',
  PROTECTION_NEEDS: 'protectionneeds',
  INCOME: 'income',
  EXPENSES: 'expenses',
  ASSETS: 'assets',
  LIABILITIES: 'liabilities',
  LIFE_PROTECTION: 'life-protection',
  CRITICAL_ILLNESS: 'ci-assessment',
  OCCUPATIONAL_DISABILITY: 'occupational-disability',
  HOSPITAL_PLAN: 'hospital-plan',
  LONG_TERM_CARE: 'long-term-care',
  INSURANCE_RESULTS: 'insurance-results'
};

export const GUIDE_ME_ROUTE_PATHS = {
  ROOT: '',
  PROFILE: GUIDE_ME_BASE_ROUTE + GUIDE_ME_ROUTES.PROFILE,
  GET_STARTED: GUIDE_ME_BASE_ROUTE + GUIDE_ME_ROUTES.GET_STARTED,
  FINANCIAL_ASSESSMENT: GUIDE_ME_BASE_ROUTE + GUIDE_ME_ROUTES.FINANCIAL_ASSESSMENT,
  INSURE_ASSESSMENT: GUIDE_ME_BASE_ROUTE + GUIDE_ME_ROUTES.INSURE_ASSESSMENT,
  PROTECTION_NEEDS: GUIDE_ME_BASE_ROUTE + GUIDE_ME_ROUTES.PROTECTION_NEEDS,
  INCOME: GUIDE_ME_BASE_ROUTE + GUIDE_ME_ROUTES.INCOME,
  EXPENSES: GUIDE_ME_BASE_ROUTE + GUIDE_ME_ROUTES.EXPENSES,
  ASSETS: GUIDE_ME_BASE_ROUTE + GUIDE_ME_ROUTES.ASSETS,
  LIABILITIES: GUIDE_ME_BASE_ROUTE + GUIDE_ME_ROUTES.LIABILITIES,
  LIFE_PROTECTION: GUIDE_ME_BASE_ROUTE + GUIDE_ME_ROUTES.LIFE_PROTECTION,
  CRITICAL_ILLNESS: GUIDE_ME_BASE_ROUTE + GUIDE_ME_ROUTES.CRITICAL_ILLNESS,
  OCCUPATIONAL_DISABILITY: GUIDE_ME_BASE_ROUTE + GUIDE_ME_ROUTES.OCCUPATIONAL_DISABILITY,
  HOSPITAL_PLAN: GUIDE_ME_BASE_ROUTE + GUIDE_ME_ROUTES.HOSPITAL_PLAN,
  LONG_TERM_CARE: GUIDE_ME_BASE_ROUTE + GUIDE_ME_ROUTES.LONG_TERM_CARE,
  INSURANCE_RESULTS: GUIDE_ME_BASE_ROUTE + GUIDE_ME_ROUTES.INSURANCE_RESULTS
};
