export const PORTFOLIO_BASE_ROUTE = '../portfolio/';

export const PORTFOLIO_ROUTES = {
  ROOT: '',
  GET_STARTED_STEP1: 'step-1',
  PERSONAL_INFO: 'personal-info',
  MY_FINANCIALS: 'my-financials',
  GET_STARTED_STEP2: 'step-2',
  RISK_ASSESSMENT:'risk-assessment',
  RISK_PROFILE:'risk-profile',
  PORTFOLIO_RECOMMENDATION:'portfolio-recommendation',
  WHATS_THE_RISK:'whats-the-risk',
  FUND_DETAILS:'fund-details'
};

export const PORTFOLIO_ROUTE_PATHS = {
  ROOT: '',
  GET_STARTED_STEP1: PORTFOLIO_BASE_ROUTE + PORTFOLIO_ROUTES.GET_STARTED_STEP1,
  PERSONAL_INFO: PORTFOLIO_BASE_ROUTE + PORTFOLIO_ROUTES.PERSONAL_INFO,
  MY_FINANCIALS: PORTFOLIO_BASE_ROUTE + PORTFOLIO_ROUTES.MY_FINANCIALS,
  GET_STARTED_STEP2: PORTFOLIO_BASE_ROUTE + PORTFOLIO_ROUTES.GET_STARTED_STEP2,
  RISK_ASSESSMENT: PORTFOLIO_BASE_ROUTE + PORTFOLIO_ROUTES.RISK_ASSESSMENT,
  RISK_PROFILE: PORTFOLIO_BASE_ROUTE + PORTFOLIO_ROUTES.RISK_PROFILE,
  PORTFOLIO_RECOMMENDATION: PORTFOLIO_BASE_ROUTE + PORTFOLIO_ROUTES.PORTFOLIO_RECOMMENDATION,
  WHATS_THE_RISK: PORTFOLIO_BASE_ROUTE + PORTFOLIO_ROUTES.WHATS_THE_RISK,
  FUND_DETAILS: PORTFOLIO_BASE_ROUTE + PORTFOLIO_ROUTES.FUND_DETAILS,

};
