export const PORTFOLIO_BASE_ROUTE = '../portfolio/';

export const PORTFOLIO_ROUTES = {
  ROOT: '',
  GET_STARTED_STEP1: 'step-1',
  PERSONAL_INFO: 'personal-info',
  MY_FINANCIALS: 'my-financials',
  GET_STARTED_STEP2: 'step-2',
  RISK_ASSESSMENT:'risk-assessment',
  RISK_PROFILE:'risk-profile'
};

export const PORTFOLIO_ROUTE_PATHS = {
  ROOT: '',
  GET_STARTED_STEP1: PORTFOLIO_BASE_ROUTE + PORTFOLIO_ROUTES.GET_STARTED_STEP1,
  PERSONAL_INFO: PORTFOLIO_BASE_ROUTE + PORTFOLIO_ROUTES.PERSONAL_INFO,
  MY_FINANCIALS: PORTFOLIO_BASE_ROUTE + PORTFOLIO_ROUTES.MY_FINANCIALS,
  RISK_ASSESSMENT: PORTFOLIO_BASE_ROUTE + PORTFOLIO_ROUTES.RISK_ASSESSMENT,
  RISK_PROFILE: PORTFOLIO_BASE_ROUTE + PORTFOLIO_ROUTES.RISK_PROFILE
};
