export let SIGN_UP_CONFIG = {
    NOTIFICATION_MAX_LIMIT: 99,
    RECENT_NOTIFICATION_COUNT: 3,
    NOTIFICATION: {
        READ_PAYLOAD_KEY: 'READ',
        DELETE_PAYLOAD_KEY: 'DELETE'
    },
    INVESTMENT: {
        RECOMMENDED: 'RECOMMENDED'
    },
    DASHBOARD: {
        PORTFOLIO_PURCHASED: 'PORTFOLIO_PURCHASED',
        ACCOUNT_CREATED: 'ACCOUNT_CREATED',
        INVESTMENT_ACCOUNT_DETAILS_SAVED: 'INVESTMENT_ACCOUNT_DETAILS_SAVED',
        CDD_CHECK_PENDING: 'CDD_CHECK_PENDING',
        RECOMMENDED: 'RECOMMENDED',
        ACCEPTED_NATIONALITY: 'ACCEPTED_NATIONALITY',
        CDD_CHECK_FAILED: 'CDD_CHECK_FAILED',
        BLOCKED_NATIONALITY: 'BLOCKED_NATIONALITY',
        EDD_CHECK_PENDING: 'EDD_CHECK_PENDING',
        EDD_CHECK_FAILED: 'EDD_CHECK_FAILED',
        ACCOUNT_SUSPENDED: 'ACCOUNT_SUSPENDED',
        ADD_POERFOLIO: 'ADD_POERFOLIO',
        DOCUMENTS_UPLOADED: 'DOCUMENTS_UPLOADED',
        EDD_CHECK_CLEARED: 'EDD_CHECK_CLEARED',
        ACCOUNT_FUNDED: 'ACCOUNT_FUNDED'
    }
};
