import { APP_ROUTES } from '../app-routes.constants';

export const PAYMENT_BASE_ROUTE = '../' + APP_ROUTES.PAYMENT + '/';

export const PAYMENT_ROUTES = {
    ROOT: '',
    CHECKOUT: 'checkout',
    PAYMENT_STATUS: 'payment-status',
    PAYMENT_INSTRUCTION: 'payment-instruction'
};

export const PAYMENT_ROUTE_PATHS = {
    ROOT: PAYMENT_BASE_ROUTE + '',
    CHECKOUT: PAYMENT_BASE_ROUTE + PAYMENT_ROUTES.CHECKOUT,
    PAYMENT_INSTRUCTION: PAYMENT_BASE_ROUTE + PAYMENT_ROUTES.PAYMENT_INSTRUCTION,
    PAYMENT_STATUS: PAYMENT_BASE_ROUTE + PAYMENT_ROUTES.PAYMENT_STATUS
};
