export const RETIREMENT_PLANNING_BASE_ROUTE = '../retirement-planning/';

export const RETIREMENT_PLANNING_ROUTES = {
  ROOT: '',
  GET_STARTED: 'get-started',
  STEP_1: 'step-1',
  STEP_2: 'step-2',
  CONFIRMATION: 'confirmation',
};

export const RETIREMENT_PLANNING_ROUTE_PATHS = {
  ROOT: '',
  GET_STARTED: RETIREMENT_PLANNING_BASE_ROUTE + RETIREMENT_PLANNING_ROUTES.GET_STARTED,
  STEP_1: RETIREMENT_PLANNING_BASE_ROUTE + RETIREMENT_PLANNING_ROUTES.STEP_1,
  STEP_2: RETIREMENT_PLANNING_BASE_ROUTE + RETIREMENT_PLANNING_ROUTES.STEP_2,
  CONFIRMATION: RETIREMENT_PLANNING_BASE_ROUTE + RETIREMENT_PLANNING_ROUTES.CONFIRMATION
};
