export const WILL_WRITING_BASE_ROUTE = '../will-writing/';

export const WILL_WRITING_ROUTES = {
  ROOT: '',
  INTRODUCTION: 'introduction',
  FAQ: 'faq',
  CHECK_ELIGIBILITY: 'eligibility',
  HOW_IT_WORKS: 'how-it-works',
  TELL_US_ABOUT_YOURSELF: 'tell-us-about-yourself',
  ABOUT_ME: 'about-me',
  MY_FAMILY: 'my-family',
  MY_CHILD_GUARDIAN: 'guardian',
  DISTRIBUTE_YOUR_ESTATE: 'distribute-your-estate',
  APPOINT_EXECUTOR_TRUSTEE: 'appoint-executor-trustee',
  MY_BENEFICIARIES: 'beneficiary',
  REVIEW_YOUR_DETAILS: 'review-your-details',
  MY_EXECUTOR_TRUSTEE: 'executor-trustee',
  MY_ESTATE_DISTRIBUTION: 'estate-distribution',
  CONFIRMATION: 'confirmation',
  VALIDATE_YOUR_WILL: 'execute-your-will',
  SIGN_UP: 'sign-up'
};

export const WILL_WRITING_ROUTE_PATHS = {
  ROOT: '',
  INTRODUCTION: WILL_WRITING_BASE_ROUTE + WILL_WRITING_ROUTES.INTRODUCTION,
  FAQ: WILL_WRITING_BASE_ROUTE + WILL_WRITING_ROUTES.FAQ,
  CHECK_ELIGIBILITY: WILL_WRITING_BASE_ROUTE + WILL_WRITING_ROUTES.CHECK_ELIGIBILITY,
  HOW_IT_WORKS: WILL_WRITING_BASE_ROUTE + WILL_WRITING_ROUTES.HOW_IT_WORKS,
  TELL_US_ABOUT_YOURSELF: WILL_WRITING_BASE_ROUTE + WILL_WRITING_ROUTES.TELL_US_ABOUT_YOURSELF,
  ABOUT_ME: WILL_WRITING_BASE_ROUTE + WILL_WRITING_ROUTES.ABOUT_ME,
  MY_FAMILY: WILL_WRITING_BASE_ROUTE + WILL_WRITING_ROUTES.MY_FAMILY,
  MY_CHILD_GUARDIAN: WILL_WRITING_BASE_ROUTE + WILL_WRITING_ROUTES.MY_CHILD_GUARDIAN,
  DISTRIBUTE_YOUR_ESTATE: WILL_WRITING_BASE_ROUTE + WILL_WRITING_ROUTES.DISTRIBUTE_YOUR_ESTATE,
  APPOINT_EXECUTOR_TRUSTEE: WILL_WRITING_BASE_ROUTE + WILL_WRITING_ROUTES.APPOINT_EXECUTOR_TRUSTEE,
  MY_BENEFICIARIES: WILL_WRITING_BASE_ROUTE + WILL_WRITING_ROUTES.MY_BENEFICIARIES,
  REVIEW_YOUR_DETAILS: WILL_WRITING_BASE_ROUTE + WILL_WRITING_ROUTES.REVIEW_YOUR_DETAILS,
  MY_EXECUTOR_TRUSTEE: WILL_WRITING_BASE_ROUTE + WILL_WRITING_ROUTES.MY_EXECUTOR_TRUSTEE,
  MY_ESTATE_DISTRIBUTION: WILL_WRITING_BASE_ROUTE + WILL_WRITING_ROUTES.MY_ESTATE_DISTRIBUTION,
  CONFIRMATION: WILL_WRITING_BASE_ROUTE + WILL_WRITING_ROUTES.CONFIRMATION,
  VALIDATE_YOUR_WILL: WILL_WRITING_BASE_ROUTE + WILL_WRITING_ROUTES.VALIDATE_YOUR_WILL,
  SIGN_UP: WILL_WRITING_BASE_ROUTE + WILL_WRITING_ROUTES.SIGN_UP
};
