export const WILL_WRITING_BASE_ROUTE = '../will-writing/';

export const WILL_WRITING_ROUTES = {
  ROOT: '',
  INTRODUCTION: 'introduction',
  FAQ: 'faq'
};

export const WILL_WRITING_ROUTE_PATHS = {
  ROOT: '',
  INTRODUCTION: WILL_WRITING_BASE_ROUTE + WILL_WRITING_ROUTES.INTRODUCTION,
  FAQ: WILL_WRITING_BASE_ROUTE + WILL_WRITING_ROUTES.FAQ,
};
