export const CORPBIZ_BASE_ROUTE = '../welcome-journey/';

export const CORPBIZ_ROUTES = {
  ROOT: '',
  TELL_ABOUT_YOU: 'welcome-tell-about-you',
  LIFE_PAYOUT: 'life-payout',
  DOWNLOAD_REPORT: 'download-report',
  GET_STARTED: 'get-started',
 
};

export const CORPBIZ_ROUTES_PATHS = {
  ROOT: '',
  GET_STARTED: CORPBIZ_BASE_ROUTE + CORPBIZ_ROUTES.GET_STARTED,
  TELL_ABOUT_YOU: CORPBIZ_BASE_ROUTE + CORPBIZ_ROUTES.TELL_ABOUT_YOU,
  LIFE_PAYOUT: CORPBIZ_BASE_ROUTE + CORPBIZ_ROUTES.LIFE_PAYOUT,
  DOWNLOAD_REPORT: CORPBIZ_BASE_ROUTE + CORPBIZ_ROUTES.DOWNLOAD_REPORT
}
