export const ACCOUNT_CREATION_BASE_ROUTE = '../investment/account/';
export const MY_INFO_START_PATH = '/investment/account/nationality';

export const ACCOUNT_CREATION_ROUTES = {
  ROOT: '',
  SELECT_NATIONALITY: 'nationality',
  PERSONAL_INFO: 'personal-info',
  RESIDENTIAL_ADDRESS: 'residential-address',
  EMPLOYMENT_DETAILS: 'employment-details',
  FINANICAL_DETAILS: 'financial-details',
  TAX_INFO: 'tax-info',
  UPLOAD_DOCUMENTS: 'upload-documents',
  PERSONAL_DECLARATION: 'persoanl-declaration',
  CONFIRM_PORTFOLIO: 'confirm-portfolio',
  ACKNOWLEDGEMENT: 'acknowledgement',
  ADDITIONALDECLARATION: 'additional-declaration',
  ADDITIONALDECLARATION_STEP1: 'additional-declaration/1',
  ADDITIONAL_DECLARATION_SCREEN_2: 'additional-declaration/2',
  SETUP_PENDING: 'status',
  UPLOAD_DOCUMENTS_BO: 'upload-documents-bo',
  START: 'start',
  FUND_INTRO: 'fund-intro'
};
export const ACCOUNT_CREATION_ROUTE_PATHS = {
  ROOT: ACCOUNT_CREATION_BASE_ROUTE + ACCOUNT_CREATION_ROUTES.ROOT,
  START: ACCOUNT_CREATION_BASE_ROUTE + ACCOUNT_CREATION_ROUTES.START,
  PERSONAL_INFO: ACCOUNT_CREATION_BASE_ROUTE + ACCOUNT_CREATION_ROUTES.PERSONAL_INFO,
  RESIDENTIAL_ADDRESS:
    ACCOUNT_CREATION_BASE_ROUTE + ACCOUNT_CREATION_ROUTES.RESIDENTIAL_ADDRESS,
  SELECT_NATIONALITY:
    ACCOUNT_CREATION_BASE_ROUTE + ACCOUNT_CREATION_ROUTES.SELECT_NATIONALITY,
  EMPLOYMENT_DETAILS:
    ACCOUNT_CREATION_BASE_ROUTE + ACCOUNT_CREATION_ROUTES.EMPLOYMENT_DETAILS,
  FINANICAL_DETAILS:
    ACCOUNT_CREATION_BASE_ROUTE + ACCOUNT_CREATION_ROUTES.FINANICAL_DETAILS,
  TAX_INFO: ACCOUNT_CREATION_BASE_ROUTE + ACCOUNT_CREATION_ROUTES.TAX_INFO,
  UPLOAD_DOCUMENTS:
    ACCOUNT_CREATION_BASE_ROUTE + ACCOUNT_CREATION_ROUTES.UPLOAD_DOCUMENTS,
  PERSONAL_DECLARATION:
    ACCOUNT_CREATION_BASE_ROUTE + ACCOUNT_CREATION_ROUTES.PERSONAL_DECLARATION,
  ADDITIONAL_DECLARATION_SCREEN_2:
    ACCOUNT_CREATION_BASE_ROUTE +
    ACCOUNT_CREATION_ROUTES.ADDITIONAL_DECLARATION_SCREEN_2,
  CONFIRM_PORTFOLIO:
    ACCOUNT_CREATION_BASE_ROUTE + ACCOUNT_CREATION_ROUTES.CONFIRM_PORTFOLIO,
  ACKNOWLEDGEMENT:
    ACCOUNT_CREATION_BASE_ROUTE + ACCOUNT_CREATION_ROUTES.ACKNOWLEDGEMENT,
  ADDITIONALDECLARATION:
    ACCOUNT_CREATION_BASE_ROUTE + ACCOUNT_CREATION_ROUTES.ADDITIONALDECLARATION,
  ADDITIONALDECLARATION_STEP1:
    ACCOUNT_CREATION_BASE_ROUTE + ACCOUNT_CREATION_ROUTES.ADDITIONALDECLARATION_STEP1,
  SETUP_PENDING: ACCOUNT_CREATION_BASE_ROUTE + ACCOUNT_CREATION_ROUTES.SETUP_PENDING,
  UPLOAD_DOCUMENTS_BO:
    ACCOUNT_CREATION_BASE_ROUTE + ACCOUNT_CREATION_ROUTES.UPLOAD_DOCUMENTS_BO,
  FUND_INTRO: ACCOUNT_CREATION_BASE_ROUTE + ACCOUNT_CREATION_ROUTES.FUND_INTRO
};
