export const INVESTMENT_COMMON_BASE_ROUTE = '../investment/';

export const INVESTMENT_COMMON_ROUTES = {
    ACKNOWLEDGEMENT: 'acknowledgement',
    CONFIRM_PORTFOLIO: 'confirm-portfolio',
    FUNDING_INSTRUCTIONS: 'funding-instructions',
    PORTFOLIO_NAMING: 'name-portfolio',
    ADD_PORTFOLIO_STATUS: 'add-portfolio-status',
};
export const INVESTMENT_COMMON_ROUTE_PATHS = {
    CONFIRM_PORTFOLIO:
        INVESTMENT_COMMON_BASE_ROUTE + INVESTMENT_COMMON_ROUTES.CONFIRM_PORTFOLIO,
    ACKNOWLEDGEMENT:
        INVESTMENT_COMMON_BASE_ROUTE + INVESTMENT_COMMON_ROUTES.ACKNOWLEDGEMENT,
    FUNDING_INSTRUCTIONS:
      INVESTMENT_COMMON_BASE_ROUTE + INVESTMENT_COMMON_ROUTES.FUNDING_INSTRUCTIONS,
    PORTFOLIO_NAMING:
        INVESTMENT_COMMON_BASE_ROUTE + INVESTMENT_COMMON_ROUTES.PORTFOLIO_NAMING,
    ADD_PORTFOLIO_STATUS:
        INVESTMENT_COMMON_BASE_ROUTE + INVESTMENT_COMMON_ROUTES.ADD_PORTFOLIO_STATUS
};
