export const INVESTMENT_COMMON_BASE_ROUTE = '../investment/';

export const INVESTMENT_COMMON_ROUTES = {
    ACKNOWLEDGEMENT: 'acknowledgement',
    CONFIRM_PORTFOLIO: 'confirm-portfolio',
    FUNDING_INSTRUCTIONS: 'funding-instructions',
    ADD_PORTFOLIO_NAME: 'add-portfolio-name',
    ADD_PORTFOLIO_STATUS: 'add-portfolio-status',
    FUND_INTRO: 'fund-intro'
};
export const INVESTMENT_COMMON_ROUTE_PATHS = {
    CONFIRM_PORTFOLIO:
        INVESTMENT_COMMON_BASE_ROUTE + INVESTMENT_COMMON_ROUTES.CONFIRM_PORTFOLIO,
    ACKNOWLEDGEMENT:
        INVESTMENT_COMMON_BASE_ROUTE + INVESTMENT_COMMON_ROUTES.ACKNOWLEDGEMENT,
    FUNDING_INSTRUCTIONS:
      INVESTMENT_COMMON_BASE_ROUTE + INVESTMENT_COMMON_ROUTES.FUNDING_INSTRUCTIONS,
    ADD_PORTFOLIO_NAME:
        INVESTMENT_COMMON_BASE_ROUTE + INVESTMENT_COMMON_ROUTES.ADD_PORTFOLIO_NAME,
    ADD_PORTFOLIO_STATUS:
        INVESTMENT_COMMON_BASE_ROUTE + INVESTMENT_COMMON_ROUTES.ADD_PORTFOLIO_STATUS,
    FUND_INTRO:
        INVESTMENT_COMMON_BASE_ROUTE + INVESTMENT_COMMON_ROUTES.FUND_INTRO
};
